allow_domains:
  - aemo.com.au
  - aemc.gov.au
  - aer.gov.au
  - cer.gov.au
  - arena.gov.au
  - cefc.com.au
  - dcceew.gov.au
  - energynetworks.com.au
  - infrastructureaustralia.gov.au
  - iea.org
  - irena.org
  - ifrs.org
  - efrag.org
  - ec.europa.eu
  - commission.europa.eu

deny_domains:
  - bbc.com
  - bloomberg.com

title_deny_regex:
  - "(webcast|podcast|register|replay)"      # junky meeting links
  - "(photo|gallery)"                        # image posts
  - "(award|awards|nominee|winners)"         # not signals
  - "(terms? & conditions|privacy|cookies)"  # legal boilerplate

keep_keywords:
  - standard
  - decision
  - guidance
  - consultation
  - regulation
  - investment
  - funding


