# Filters for GG Advisory digest automation
# Applied automatically in src/generate_monthly.py

allow_domains:
  - aemo.com.au
  - aemc.gov.au
  - aer.gov.au
  - cer.gov.au
  - arena.gov.au
  - cefc.com.au
  - dcceew.gov.au
  - infrastructureaustralia.gov.au
  - energynetworks.com.au
  - ifrs.org
  - efrag.org
  - globalreporting.org
  - fsb-tcfd.org
  - asic.gov.au
  - iea.org
  - irena.org
  - australianinvestmentcouncil.com.au
  - bnef.com
  - ec.europa.eu         # ‚Üê NEW

deny_domains:
  # Filter social media, marketing mirrors, and non-official distributors
  - facebook.com
  - x.com
  - twitter.com
  - linkedin.com
  - youtube.com
  - medium.com
  - mailchi.mp
  - substack.com
  - eventbrite.com

title_deny_regex:
  # Exclude low-value categories and non-informative posts
  - "(?i)newsletter(?!.*(ifrs|issb|efrag))"
  - "(?i)subscribe|sign[- ]?up|mailing list"
  - "(?i)events?\\b|webinar|conference|roundtable|workshop|training"
  - "(?i)careers?|job opening|vacan(cy|cies)|appl(y|ications?)"
  - "(?i)podcast|video|watch|livestream"
  - "(?i)tender|procurement|request for (tender|proposal)"
  - "(?i)photo gallery|highlights|our people|community update"
  - "(?i)award|finalist|shortlist|nominee"
  - "(?i)opinion|editorial|blog|insight|commentary"

keep_keywords: []
