sections:
  Energy Transition:
    rss:
      - https://www.dcceew.gov.au/about/news/stay-informed/rss
    html:
      - https://www.aemo.com.au/newsroom
      - https://www.aemo.com.au/newsroom/media-release
      - https://www.aemc.gov.au/news-centre
      - https://www.aer.gov.au/news
      - https://www.cer.gov.au/news-and-media/news
      - https://arena.gov.au/news/
      - https://www.cefc.com.au/media/?type=media+release
      - https://www.energynetworks.com.au/news/
      - https://www.infrastructureaustralia.gov.au/news-media
      - https://www.iea.org/news
      - https://www.irena.org/news

  ESG Reporting:
    rss: []
    html:
      - https://www.ifrs.org/news-and-events/updates/issb/
      - https://www.ifrs.org/news-and-events/news/
      - https://www.efrag.org/en/news-and-calendar/news
      - https://www.efrag.org/en/updates
      - https://www.globalreporting.org/news/
      - https://www.fsb-tcfd.org/publications/
      - https://asic.gov.au/about-asic/news-centre/find-a-media-release/
      - https://www.dcceew.gov.au/about/news

  Sustainable Finance & Investment:
    rss: []
    html:
      - https://arena.gov.au/funding/
      - https://arena.gov.au/news/
      - https://www.cefc.com.au/media/?type=media+release
      - https://www.cleanenergyfinancecorp.com.au/media/?type=in+the+news
      - https://www.australianinvestmentcouncil.com.au/news
      - https://about.bnef.com/blog/
      - https://www.irena.org/Newsroom/Articles
